### PR TITLE
Use mqtt service instead of calling GET /status every 5 seconds.

### PR DESCRIPTION
**Pull request by sofyakurilova**
3PjUBLGrQC5dYMJ

Video after changes
https://screencast.googleplex.com/cast/NTgzMjA1ODE1NTgyNzIwMHwzODc4MGJkMi1jMQ

### CODE REVIEW

**Review by hitnik — APPROVED** [review]

**Comment by jboddey** [comment]
This is not quite working for me. When you start a Testrun the Waiting for Device status is shown but quickly goes back to this view:

image

**Comment by sofyakurilova** [comment]
> This is not quite working for me. When you start a Testrun the Waiting for Device status is shown but quickly goes back to this view:

@hitnik can you please check what status is returned by mqtt when testrun is started?

**Comment by sofyakurilova** [comment]
The issue is on FE side

**Comment by hitnik** [comment]
> @hitnik The JSON being sent to the UI in MQTT is as follows: https://paste.googleplex.com/6069255923826688 There are some issues with it, the device is being sent as a Python object and the started datetime was too but this paste does not show it as I fixed it to debug.

Got it, I'm working on it.

**Review by jboddey — APPROVED** [review]

**Pull request merged**
