### PR TITLE
Jinja reports

### PR DESCRIPTION
**Pull request by hitnik**
test report example 
[2024-08-23T14_11_54.pdf](https://github.com/user-attachments/files/16728964/2024-08-23T14_11_54.pdf)

risk_profile example 
[test_risk_report.pdf](https://github.com/user-attachments/files/16728970/test_risk_report.pdf)

### CODE REVIEW

**Comment by jboddey** [comment]
The margin above the word 'Test status' is too low, it is not aligned with 'Device configuration'. I think Test status and Test result should also be capitalized (Test Status and Test Result).

**Comment by jhughesbiot** [comment]
Page numbers are wrong on module report pages

**Comment by jboddey** [comment]
@hitnik There's a merge conflict to resolve here

**Comment by hitnik** [comment]
> 'Device configuration'.

Fixed 
[2024-09-03T13_28_50.pdf](https://github.com/user-attachments/files/16868171/2024-09-03T13_28_50.pdf)

**Comment by hitnik** [comment]
> Page numbers are wrong on module report pages

The page numbering works correctly; I uploaded a bad example in which the numbering was not implemented.

**Review by jboddey — APPROVED** [review]

**Review by jhughesbiot — APPROVED** [review]

**Pull request merged**
