### PR TITLE
Show risk for each question in the Risk profile

### PR DESCRIPTION
**Pull request by hitnik**

### CODE REVIEW

**Comment by jboddey** [comment]
Could you paste an image of the output of this?

**Comment by hitnik** [comment]
> Could you paste an image of the output of this?

Screenshot 2024-07-31 14 48 28

**Comment by hitnik** [comment]
> > > Could you paste an image of the output of this?
> > 
> > 
> > Screenshot 2024-07-31 14 48 28
> 
> Looks like this has broken the formatting of short answer fields?

Before my changes 

Screenshot 2024-07-31 21 13 33

After  my changes

Screenshot 2024-07-31 21 14 12

**Comment by jboddey** [comment]
The current profile looks like this in PDF format: 
image

Are you viewing raw HTML?

**Comment by hitnik** [comment]
> The current profile looks like this in PDF format: 
> image
> 
> Are you viewing raw HTML?

Yes, I will check PDF.

**Comment by hitnik** [comment]
> > The current profile looks like this in PDF format:
> > image
> > Are you viewing raw HTML?
> 
> Yes, I will check PDF.

PDFs

before
Screenshot 2024-08-01 12 01 17

after
Screenshot 2024-08-01 12 01 46

**Review by jboddey — APPROVED** [review]

**Pull request merged**
