### PR TITLE
Hotfix 1.2.1

### PR DESCRIPTION
**Pull request by jhughesbiot**
Fix modbus test crash when compliant

### CODE REVIEW

**Comment by jboddey** [comment]
Also, whilst I was looking at this, I found that there should be extra logic in the test module base code where checking what is returned by each test. Where we check if the result is equal to error, we need to add an else statement. Could you add this whilst I'm away?

**Comment by jhughesbiot** [comment]
> Also, whilst I was looking at this, I found that there should be extra logic in the test module base code where checking what is returned by each test. Where we check if the result is equal to error, we need to add an else statement. Could you add this whilst I'm away?

Do we just want to make this an else statement? I don't actually see any benefit for specifically checking for error

**Comment by jboddey** [comment]
> > Also, whilst I was looking at this, I found that there should be extra logic in the test module base code where checking what is returned by each test. Where we check if the result is equal to error, we need to add an else statement. Could you add this whilst I'm away?
> 
> Do we just want to make this an else statement? I don't actually see any benefit for specifically checking for error

Yes exactly, the else will then return 'Error'

**Comment by jhughesbiot** [comment]
Updated to handle unknown result values

**Review by jboddey — APPROVED** [review]

**Pull request merged**
