### PR TITLE
Copy a device profile  questionnaire to risk profile

### PR DESCRIPTION
**Pull request by hitnik**
[profile.pdf](https://github.com/user-attachments/files/17279641/profile.pdf)

### CODE REVIEW

**Comment by hitnik** [comment]
[profile.pdf](https://github.com/user-attachments/files/17279624/profile.pdf)

**Comment by KrystsinaT** [comment]
@jboddey I see the questions added from the Device profile are shown without risk estimations. Confirm please if it is ok.

**Comment by jboddey** [comment]
>  @jboddey I see the questions added from the Device profile are shown without risk estimations. Confirm please if it is ok.

We will need the risk label on device type and sensitive info question. The risks for these questions should then also update the overall device risk

**Comment by hitnik** [comment]
> > @jboddey I see the questions added from the Device profile are shown without risk estimations. Confirm please if it is ok.
> 
> We will need the risk label on device type and sensitive info question. The risks for these questions should then also update the overall device risk

@jboddey  Done.

**Review by OlgaMardvilko — APPROVED** [review]

**Comment by hitnik** [comment]
[profile.pdf](https://github.com/user-attachments/files/17305652/profile.pdf)
@KrystsinaT  Here's a sample report for you to review.

**Review by KrystsinaT — COMMENTED** [review]
The font of Question/Answer should be changed by design, the paging should be added

**Comment by hitnik** [comment]
> @hitnik The font of Question/Answer should be changed by design, the paging should be added

@KrystsinaT  Fixed 
[profile.pdf](https://github.com/user-attachments/files/17306900/profile.pdf)

**Review by KrystsinaT — COMMENTED** [review]
Verified. Paging and font are shown as expected. Thank you!

**Pull request merged**
