### PR TITLE
Feature/tls module report

### PR DESCRIPTION
**Pull request by jhughesbiot**
- Add TLS module report back with updated module report style
- Increase TLS module timeout

### CODE REVIEW

**Comment by jboddey** [comment]
Note: @jboddey to check the design of this.

**Comment by jboddey** [comment]
New PDF report design:
image

**Comment by jhughesbiot** [comment]
> Note: I have removed the issuer information as I don't think that is really required here. We are only interested in the device cert and that it has been signed by a known CA.

The Issuer gives the signer information though, isn't that relevant?

Also, do you have a device that resolves multiple certificates to test?  That is where I have seen formatting issues on pagination.

**Comment by jboddey** [comment]
I think as long as the cert has been signed, the signed by field will be provided and the user should know the details of the issuer. Also, I'm struggling to find a place for the issuer information. I will try with a device with multiple TLS certificates.

**Comment by duncangreene** [comment]
Will this proposed section in the report provide context as to _why_ the the TLS 1.2 and TLS 1.3 certs are being reported as invalid when the user sees them in the results list below?

image

Sort of akin to how the user might see it in Google Chrome?

image

**Comment by duncangreene** [comment]
> This PR will not address that particular request. Please could you raise a feature request detailing this and we will take a look?

#955

**Comment by hitnik** [comment]
@jboddey  I have added splitting by module summary and refactored the formatting of the report module.   Could you check this on a real report?

**Comment by jboddey** [comment]
@hitnik Looks a lot better. Just some small things:

image

We could do with right padding on the signed by property.
We need margin top on the summary bar for the non-first pages.

**Comment by hitnik** [comment]
@jboddey  I reduced the module-summary font from 24 to 22, added padding on the right, and also added a margin-top of 10 for non-first pages.

**Review by jboddey — APPROVED** [review]

**Pull request merged**
