### PR TITLE
Pin python requirements

### PR DESCRIPTION
**Pull request by jhughesbiot**
Use semi-automatic process of determining existing stable python dependencies and manually updating requirements.txt file.

### CODE REVIEW

**Comment by jboddey** [comment]
Looks good. However, could you briefly explain how this works and the use of these files:
image

Also, is there anyway we could run this command without sudo?

**Review by swapnilGirishPawar — COMMENTED** [review]
New changes looks good to me,

**Comment by jboddey** [comment]
Note: Comment out bin script to use as reference, rest is fine to merge.

**Comment by jhughesbiot** [comment]
> Note: Comment out bin script to use as reference, rest is fine to merge.

This should be ready to go now.

**Review by jboddey — APPROVED** [review]

**Pull request merged**
