### PR TITLE
Write container logs to file

### PR DESCRIPTION
**Pull request by jboddey**

### CODE REVIEW

**Comment by jhughesbiot** [comment]
Inspecting the docker logs and comparing them to the module.log reveals that the module exits too fast for the log stream to be fully handled and does not obtain the full logs.

**Comment by jhughesbiot** [comment]
Unrelated to this PR but this branch currently contains a call to an old method that doesn't exist so an error is thrown during the report generation so need to make sure that merging does not re-introduce this issue

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/testrun/framework/python/src/core/testrun.py", line 415, in _device_stable
    result = self._test_orc.run_test_modules()
  File "/usr/local/testrun/framework/python/src/test_orc/test_orchestrator.py", line 118, in run_test_modules
    self.get_session().set_report_url(report.get_report_url())
AttributeError: 'TestRunSession' object has no attribute 'set_report_url'
```

**Comment by jboddey** [comment]
> Unrelated to this PR but this branch currently contains a call to an old method that doesn't exist so an error is thrown during the report generation so need to make sure that merging does not re-introduce this issue
> 
> ```
> Traceback (most recent call last):
>   File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
>     self.run()
>   File "/usr/lib/python3.8/threading.py", line 870, in run
>     self._target(*self._args, **self._kwargs)
>   File "/usr/local/testrun/framework/python/src/core/testrun.py", line 415, in _device_stable
>     result = self._test_orc.run_test_modules()
>   File "/usr/local/testrun/framework/python/src/test_orc/test_orchestrator.py", line 118, in run_test_modules
>     self.get_session().set_report_url(report.get_report_url())
> AttributeError: 'TestRunSession' object has no attribute 'set_report_url'
> ```

@jhughesbiot The set_report_url method is present in this branch, perhaps you had some issue with Git when checking this branch out? I have updated the logging method as per your suggestion and it seems to work as expected now, thanks! Could you finish reviewing this PR?

**Comment by jboddey** [comment]
Closing this PR now that v1.1.1 has already been released. This code change is now in release/v1.1.2

**Pull request closed without merging**
